export const UPDATE_PERSON = 'UPDATE_PERSON'
export const RESET_PERSON = 'RESET_PERSON'

export const SET_REDIRECT = 'SET_REDIRECT'
export const RESET_REDIRECT = 'RESET_REDIRECT'

export const UPDATE_TOAST = 'UPDATE_TOAST'
export const RESET_TOAST = 'RESET_TOAST'
